### PR TITLE
Add Turkish Translations

### PR DESCRIPTION
**Pull request by kzorluoglu**
Missing Turkish Langage

### CODE REVIEW

**Review by jrushlow — CHANGES_REQUESTED** [review]
thanks @kzorluoglu for the translation. If you could change the first letter of each translation to lower case, we should be able to get this merged and release pretty quick. 

For additional context - 

EN: This token will expire in 5 minutes.
TR: Bu jetonun süresi 5 dakika içinde sona erecek.

check out https://github.com/SymfonyCasts/reset-password-bundle/pull/164

**Comment by kzorluoglu** [comment]
allrigt, i applied the requested changed. Thanks for feedback!

**Review by jrushlow — APPROVED** [review]
Awesome! Thank you @kzorluoglu

**Comment by weaverryan** [comment]
Thanks Koray!

**Pull request merged**
